server:
  port: 9024
  servlet:
    context-path: /wx

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wx?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: wx
    password: Wx@20190818
    platform: mysql


mybatis:
  mapper-locations:
    - classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.togo.wx

logging:
  level:
    mapping : debug

app:
  wx:
    loginUrl: https://api.weixin.qq.com/sns/jscode2session
    secret: 8820b6bfaa0ac308e199e79bd66557e6
    appId: wx0d3a6e8a8b72c04b